### ISSUE TITLE
Front-end of TestData Generator does not support list of source and destination

### ISSUE THREAD

**Issue by ShaikDayan** [openepcis/epcis-testdata-generator#11]
According to GS1 standard we need to have multiple source and destination in an event

**Comment by Aravinda93** [comment]
This issue has been fixed and currently available within the feature branch of the project: [fixing_issues_based_on_testing](https://github.com/openepcis/epcis-testdata-generator/tree/fixing_issues_based_on_testing).

Will inform again after fixing other issues to test all the issues again together.
