### ISSUE TITLE
Parent counts are not considered in subsequent child nodes

### ISSUE THREAD

**Issue by ShaikDayan** [openepcis/epcis-testdata-generator#13]
If we mention the parent count and points to other child identifier, it is not consider while submitting the design

**Comment by Aravinda93** [comment]
This issue has been fixed and currently available within the feature branch of the project: [fixing_issues_based_on_testing](https://github.com/openepcis/epcis-testdata-generator/tree/fixing_issues_based_on_testing).

Will inform again after fixing other issues to test all the issues again together.
