### ISSUE TITLE
Transformation id is not added to the Event

### ISSUE THREAD

**Issue by ShaikDayan** [openepcis/epcis-testdata-generator#14]
When we mention the transformation id, it is not added to the event generated. Also UOM liter is missing

**Comment by Aravinda93** [comment]
This issue has been fixed and currently available within the feature branch of the project: [fixing_issues_based_on_testing](https://github.com/openepcis/epcis-testdata-generator/tree/fixing_issues_based_on_testing). 

Will confirm after the merge for testing the changes again.
