### ISSUE TITLE
TransactionEvent MUST have a bizTransactionList

### ISSUE THREAD

**Issue by RalphTro** [openepcis/epcis-testdata-generator#35]
Dear @Aravinda93 ,
Another thing to further improve this great tool: Right now, it is possible to generate TransactionEvents without a bizTransaction List. 
However, this is required (it does not validate against the JSON schema/XSD otherwise) as of the EPCIS standard. 
Please implement some measure to enforce that this at least one bizTransactionID is specified by the user. 
Many thanks in advance and kind regards,
Ralph

**Comment by Aravinda93** [comment]
Dear @RalphTro 

This issue has been fixed and changes are currently present within the feature branch `feature/OEPCIS-662_support_inheritence_of_the_parent_identifier`. Will inform you once it has been deployed.

Meanwhile, we have deployed the latest version in prod https://test-data-generator.openepcis.io/ and you should be able to see fixes for the following issues:

https://github.com/openepcis/epcis-testdata-generator/issues/30
https://github.com/openepcis/epcis-testdata-generator/issues/29

Have a nice weekend ahead :)

**Comment by RalphTro** [comment]
Dear @Aravinda93 ,
Many thanks for adjusting #29 and #30 as well as addressing this matter! 
Kind regards and have a great start into the new week;
Ralph

**Comment by RalphTro** [comment]
Many thanks for implementing this, @Aravinda93 and @sboeckelmann !
