### ISSUE TITLE
Add field 'certificationInfo'

### ISSUE THREAD

**Issue by RalphTro** [openepcis/epcis-testdata-generator#7]
Dear @Aravinda93 ,

Please add support for the field '`certificationInfo`'. The latter is applicable for all EPCIS event types (see EPCIS 2.0, section 7.4.1) and expects a URI. 

In the Create Test Data UI, my suggestion is to add the field as part of the 'OTHER' category, followed by 'Extensions'. 

What do you think?

Many thanks in advance and kind regards,
Ralph

**Comment by Aravinda93** [comment]
Dear @RalphTro 

Just wanted to update you that we have taken care of this issue and the changes are currently present within the feature branch `feature/OEPCIS-471-add_additional_attributes_to_events`.

We will merge the changes to the `main` branch along with the fix to the issue: https://github.com/openepcis/epcis-testdata-generator/issues/8. We will update you as soon as we have merged the changes.

Thanks and best regards,
Aravinda
